.PHONY:gen-frontend
gen-frontend:
   gomall0/app/frontend                                                                                                                             
▶ cwgo server --type HTTP --idl  ../../idl/frontend/auth.proto --service frontend -I ../../   