// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/cloudwego/gomall07/app/frontend/biz/router"
	butils "github.com/cloudwego/gomall07/app/frontend/biz/utils"
	"github.com/cloudwego/gomall07/app/frontend/conf"
	"github.com/cloudwego/gomall07/app/frontend/infra/rpc"
	"github.com/cloudwego/gomall07/app/frontend/middleware"
	frontendutils "github.com/cloudwego/gomall07/app/frontend/utils"
	"github.com/cloudwego/gomall07/common/mtl"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	hertzobslogrus "github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"github.com/joho/godotenv"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

var (
	ServiceName  = frontendutils.ServiceName
	MetricsPort  = conf.GetConf().Hertz.MetricsPort
	RegistryAddr = conf.GetConf().Hertz.RegistryAddr
)

func main() {
	_ = godotenv.Load()
	p := mtl.InitTracing(ServiceName)
	defer p.Shutdown(context.Background())
	// init dal
	// dal.Init()
	consul, registryIndo := mtl.InitMetric(ServiceName, MetricsPort, RegistryAddr)
	defer consul.Deregister(registryIndo)
	rpc.Init()
	address := conf.GetConf().Hertz.Address // 从配置中获取服务器的监听地址

	tracer, cfg := hertztracing.NewServerTracer()

	h := server.New(server.WithHostPorts(address),
		server.WithTracer(prometheus.NewServerTracer("", "", prometheus.WithDisableServer(true),
			prometheus.WithRegistry(mtl.Registry),
		)),
		tracer,
	) // 创建一个 Hertz 服务器实例，并指定监听的地址和端口
	h.Use(hertztracing.ServerMiddleware(cfg))
	registerMiddleware(h) // 为服务器注册全局中间件

	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) { // 测试路由
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	router.GeneratedRegister(h) // 注册生成的路由

	h.LoadHTMLGlob("template/*") // 用于加载template下html文件
	h.Static("/static", "./")    // 查找静态目录

	// 新增sign-in的路由
	h.GET("/sign-in", func(c context.Context, ctx *app.RequestContext) { // 测试路由
		message := ctx.GetString("message")
		fmt.Println("sign_in_router_message:", message)
		data := utils.H{
			"Title":   "Sign In",
			"Next":    ctx.Query("next"),
			"message": message,
		}

		ctx.HTML(consts.StatusOK, "sign-in", data)
	})

	// 新增sign-up的路由
	h.GET("/sign-up", func(c context.Context, ctx *app.RequestContext) { // 测试路由
		ctx.HTML(consts.StatusOK, "sign-up", utils.H{"Title": "Sign Up"})
	})

	// 新增aboutluyou
	h.GET("/about", func(c context.Context, ctx *app.RequestContext) {
		hlog.CtxInfof(c, "CloudWeGo shop about page")
		fmt.Println("into_main_/about")

		// 假设 resp 是一个包含页面基本数据的 map，这里简单初始化
		resp := map[string]any{
			"Title": "About",
		}

		ctx.HTML(consts.StatusOK, "about", butils.WarResponse(c, ctx, resp))
	})

	h.GET("/error", func(c context.Context, ctx *app.RequestContext) {
		ctx.HTML(401, "error", map[string]interface{}{
			"ErrorMessage": "请先注册登录",
		})
	})

	h.Spin()
}

func registerMiddleware(h *server.Hertz) {
	store, _ := redis.NewStore(10, "tcp", conf.GetConf().Redis.Address, "", []byte(os.Getenv("SESSION_SECRET")))
	h.Use(sessions.New("cloudwego-shop", store))

	h.Use(middleware.JWT())
	// log
	logger := hertzobslogrus.NewLogger(hertzobslogrus.WithLogger(hertzlogrus.NewLogger().Logger()))
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())

	var flushInterval time.Duration
	if os.Getenv("GO_ENV") == "online" {
		flushInterval = time.Minute
	} else {
		flushInterval = time.Second
	}

	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: flushInterval,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())

	middleware.Register(h)
}
